#include <cstdio>
#include <cstdint>
#include <string>
#include <vector>
#include <cinttypes>
#include <filesystem>
#include <cstdarg>
#include <array>

// rand source is /dev/urandom, single cycle, average displacement distance of 50.02
constexpr uint16_t PBOX[] = {
   59,  89,  40,  81,  70, 119,  56,  61, 115,  57, 125,  55, 124,  41, 122,  50,
  120,  76,  98,  53,   8, 109, 100,  49,  51, 108,  83,  13,  87,  32, 123, 110,
   75,  94, 113,  69, 118,  47,  26,  58, 105,  72, 117,  68,  25,   1,  30, 121,
   11,  34,  88,  43,  79, 127,  95,  84,  96,  35,  48,  74,  62,  67,  42, 114,
  111,  73,  64, 102,  71,  44,  91,  90,   3,  78,   5, 106,  37, 103,  54,  27,
  116,  28,  16,  10,  33,  80,  20,  66,  60,  46,  22,  29,   4,   6,  99,  63,
   18,  23,  24,  38, 107,  39,  31, 101,  17,  92,  97, 126, 112,  93,  77,   2,
  104,   7,  85,  19,   9,  21,  82,  65,  12,  86,   0,  36,  15,  14,  52,  45,
};

constexpr auto make_pbox_fast_table() {
  std::array<std::array<__uint128_t, 256>, 16> table{};
  for (int i = 0; i < 16; ++i) {
    for (int v = 0; v < 256; ++v) {
      table[i][v] = 0;
      for (int j = 0; j < 8; ++j) {
        table[i][v] |= (__uint128_t) ((v >> j) & 0x1) << PBOX[i * 8 + j];
      }
    }
  }
  return table;
}
static constexpr auto PBOX_FAST_TABLE = make_pbox_fast_table();

constexpr int32_t NR_SBOX_BITS = 8;
constexpr uint32_t SBOX_MASK = (1 << NR_SBOX_BITS) - 1;
// generated with GF(256) inv with seed = b'114514', nonlinearity=112, diff. uniformity=4, no fixed point
constexpr uint16_t SBOX[] = {
  0x52, 0xf8, 0xef, 0xe4, 0x92, 0xe6, 0x59, 0x23, 0x5a, 0xc1, 0xed, 0x4f, 0x99, 0xb4, 0xbb, 0xd9,
  0x8b, 0x96, 0x28, 0xce, 0x26, 0xde, 0x42, 0x07, 0x91, 0x17, 0x39, 0x04, 0x0a, 0x13, 0x66, 0xaa,
  0xb2, 0x3a, 0xa2, 0x72, 0x70, 0xf2, 0x1b, 0xa1, 0xe5, 0x25, 0x8c, 0x31, 0xc5, 0x1c, 0x6c, 0x7c,
  0x48, 0xb6, 0xfb, 0x09, 0x41, 0x2b, 0x7e, 0x20, 0xeb, 0x60, 0x03, 0x90, 0x12, 0x44, 0x3b, 0x7a,
  0x75, 0xa0, 0x53, 0xd4, 0xe2, 0x6f, 0x7d, 0xac, 0xc9, 0x4d, 0x82, 0x0d, 0xda, 0xa6, 0xf0, 0xbc,
  0xff, 0x9e, 0xf7, 0x38, 0x58, 0x0c, 0x98, 0x4b, 0xd0, 0xbd, 0x30, 0xd8, 0x7f, 0x55, 0xe8, 0x02,
  0xa8, 0xad, 0x8d, 0x10, 0xfd, 0x63, 0xf9, 0x8a, 0xd7, 0x85, 0x62, 0x5b, 0x5c, 0x51, 0xa9, 0x18,
  0x6a, 0x0f, 0x5e, 0xab, 0x94, 0x3c, 0xee, 0x8e, 0xa5, 0x84, 0x89, 0x6e, 0xf5, 0xaf, 0xa4, 0x3d,
  0x97, 0xfc, 0x56, 0x0e, 0xf4, 0x1d, 0xe1, 0xe9, 0x15, 0xb0, 0x6d, 0x67, 0x4e, 0x61, 0x77, 0x50,
  0xf1, 0x35, 0xf6, 0xa3, 0xcd, 0x79, 0x01, 0xb7, 0x74, 0x9b, 0x1a, 0x4a, 0x36, 0xc2, 0xe0, 0xbf,
  0x05, 0xcf, 0x7b, 0xd6, 0xdc, 0xdd, 0xe7, 0x57, 0x3f, 0x0b, 0xa7, 0x64, 0x37, 0x88, 0xba, 0x71,
  0x19, 0x1e, 0x46, 0xcc, 0x3e, 0x21, 0xc0, 0x2e, 0xfa, 0x76, 0xb8, 0x24, 0x78, 0xd2, 0x32, 0x43,
  0x8f, 0x47, 0xd1, 0xc6, 0xfe, 0x86, 0x11, 0x80, 0xb1, 0x95, 0x4c, 0x5d, 0x49, 0x93, 0x14, 0x22,
  0xf3, 0xc4, 0x27, 0xdb, 0xea, 0x54, 0x2d, 0x69, 0xc7, 0xd3, 0x40, 0x2c, 0x29, 0x9c, 0xc8, 0x9f,
  0x33, 0xb3, 0xb5, 0xc3, 0x73, 0x2a, 0x9d, 0xbe, 0x16, 0x6b, 0x1f, 0x87, 0x34, 0xd5, 0xec, 0x00,
  0x08, 0x9a, 0x81, 0xca, 0x06, 0x2f, 0xcb, 0x45, 0x68, 0x83, 0x65, 0x5f, 0xae, 0xe3, 0xb9, 0xdf,
};

#define build_u128(hi, lo) (((__uint128_t) (hi) << 64) | (lo))
#define lo(x) ((uint64_t) ((x) & 0xFFFFFFFFFFFFFFFF))
#define hi(x) ((uint64_t) ((x >> 64) & 0xFFFFFFFFFFFFFFFF))

constexpr int32_t BLOCK_SIZE = 512; // byte
constexpr int32_t NR_ROUND = 16;
constexpr __uint128_t STATE0 = build_u128(0x69879d90d86d7e20, 0x384230e4dc4235d9); // generated by /dev/urandom
constexpr __uint128_t PHI_INV = build_u128(0x9E3779B97F4A7C15,  0xF39CC0605CEDC835); // 2^128 / phi

__uint128_t rotshl(__uint128_t a, uint32_t b) {
  b &= 127;
  if (b == 0) return a;
  return (a << b) | (a >> (128 - b));
}

__uint128_t replace_with_sbox(__uint128_t state, const uint16_t sbox[]) {
  __uint128_t res = 0;
  for (int i = 0; i < 128; i += NR_SBOX_BITS) {
    res |= (__uint128_t) sbox[(state >> i) & SBOX_MASK] << i;
  }
  return res;
}

__uint128_t shuffle_with_pbox(__uint128_t state, const uint16_t pbox[]) {
  __uint128_t res = 0;
  for (int i = 0; i < 16; i++) {
    res |= PBOX_FAST_TABLE[i][(state >> i * 8) & 0xFF];
  }
  return res;
}

std::string exename;
int ret = 0;

int output_error(const char* msg_fmt, ...) {
  fprintf(stderr, "%s: ", exename.c_str());
  va_list args;
  va_start(args, msg_fmt);
  vfprintf(stderr, msg_fmt, args);
  va_end(args);
  fprintf(stderr, "\n");
  ret = 1;
  return 0;
}

__uint128_t round_func(__uint128_t state) {
  for (int32_t r = 0; r < NR_ROUND; r++) {
    state = replace_with_sbox(state, SBOX);
    state = shuffle_with_pbox(state, PBOX);
    state ^= (state >> 23) ^ (state << 41);
    state *= PHI_INV * (r + 1);
  }
  return state;
}

__uint128_t compress(FILE* input_fp, std::string filename, int& error) {
  constexpr int32_t INBUF_SIZE = 64 * 1024;
  static uint8_t ibuf[INBUF_SIZE];
  uint8_t *ie = ibuf + INBUF_SIZE, *ip = ie;

  uint64_t bit_len = 0;

  auto read_u8 = [&]() -> uint8_t {
    if (ip == ie) {
      ie = ibuf + fread(ibuf, sizeof(uint8_t), INBUF_SIZE, input_fp);
      ip = ibuf;
      if (ip == ie) return 0;
    }
    bit_len++;
    return *ip++;
  };

  __uint128_t state = STATE0;

  while (!feof(input_fp)) {
    for (int32_t i = 0; i < BLOCK_SIZE; i++) {
      uint8_t byte = read_u8();
      (state ^= byte) *= PHI_INV * (i + 1);
      state = rotshl(state, 13);
    }

    state = round_func(state);
  }

  state ^= ((__uint128_t) bit_len << 64) | bit_len;
  state = round_func(state);


  error = 0;
  if (ferror(input_fp)) {
    output_error("unkown error occurred when reading file `%s`.", filename.c_str());
    error = 1;
  }

  return state;
}

int output_line(__uint128_t hash, std::string filename) {
  // TODO: use `ls --quoting=shell-escape` style to escape filename
  fprintf(stdout, "%016" PRIx64 "%016" PRIx64 "  %s\n", hi(hash), lo(hash), filename.c_str());
  return 0;
}

struct CheckLine {
  __uint128_t hash; std::string filename;
};

int getline(char* buf, FILE* in) {
  char c, *p = buf;
  while (c = fgetc(in), c == ' ');
  for (; c != '\n' && c != '\r' && c != EOF; c = fgetc(in)) *p++ = c;
  return p - buf;
}

std::vector<CheckLine> analysis_checksum_file(FILE* checksum_fp) {
  std::vector<CheckLine> res;

  uint64_t hi, lo;
  static char filename[512];

  while (!feof(checksum_fp)) {
    int ret = fscanf(checksum_fp, "%016" PRIx64 "%016" PRIx64 "  %s", &hi, &lo, filename);
    if (ret != 3) {
      static char line[512];
      int line_size = getline(line, checksum_fp);
      if (line_size > 0 && line[0] != '#') {
        output_error("failed to parse line `%*s`. skipped.", line);
      }
      continue;
    }
    // TODO: use `ls --quoting=shell-escape` style to escape filename
    res.push_back({ build_u128(hi, lo), filename });
  }

  return res;
}

FILE* fopen_with_log(const char* filename, const char* mode) {
  if (std::filesystem::is_directory(filename)) {
    output_error("`%s` is a dir.", filename);
    return nullptr;
  }
  FILE* fp = fopen(filename, mode);
  if (fp == nullptr) {
    output_error("cannot open or read file `%s`.", filename);
  }
  return fp;
}

int main(int argc, char** argv) {
  exename = argv[0];
  auto shift = [&]() { argc--; argv++; };

  bool stdin_occurred = false;
  bool escape_mode = false;
  bool check_mode = false;

  struct FileWithName { FILE* fp; std::string name; };
  std::vector<FileWithName> input_files;

  for(shift(); argc; shift()) {
    std::string arg = argv[0];
    if (!escape_mode && arg == "--") escape_mode = true;
    else if (!escape_mode && (arg == "-c" || arg == "--check")) check_mode = true;
    else if (!escape_mode && (arg == "-h" || arg == "--help")) {
      fprintf(stdout, "Usage: %s [-h|--help] [-c|--check] [<FILE>]...\n", exename.c_str());
      return 0;
    } else {
      if (!escape_mode && arg == "-") {
        if (!stdin_occurred) {
          input_files.push_back({stdin, "-"});
          stdin_occurred = true;
        }
        continue;
      }
      FILE* fp = fopen_with_log(arg.c_str(), "rb");
      if (fp == nullptr) continue;
      input_files.push_back({fp, arg});
    }
  }

  if (ret == 0 && input_files.size() == 0) input_files.push_back({stdin, "-"});

  if (check_mode) {
    for (auto& checksum_file : input_files) {
      auto files = analysis_checksum_file(checksum_file.fp);
      for (auto file : files) {
        FILE* fp = fopen_with_log(file.filename.c_str(), "rb");
        if (fp == nullptr) continue;
        int error = 0;
        __uint128_t hash = compress(fp, file.filename, error);
        if (!error) fprintf(stdout, "%s: %s\n", file.filename.c_str(), hash == file.hash ? "OK" : "FAILED");
        ret |= error || hash != file.hash;
      }
    }
  } else {
    for (auto& file : input_files) {
      int error = 0;
      auto hash = compress(file.fp, file.name, error);
      if (!error) output_line(hash, file.name);
    }
  }

  for (auto& input_file : input_files) {
    if (input_file.fp && input_file.fp != stdin) fclose(input_file.fp);
  }

  return ret;
}
