#include <cstdio>
#include <cstdint>
#include <string>
#include <vector>
#include <cinttypes>
#include <filesystem>
#include <cstdarg>

#include "uint256_t.h"

constexpr int32_t BLOCK_SIZE = 64; // byte
constexpr int32_t NR_ROUND = 64;
// generated by /dev/urandom
const uint256_t H0 = uint256_t(0x33804c69e3392e42, 0xb4ee7b3011acfdd3, 0xcbd7835251a4e165, 0x0c338280c6397a25);
const uint256_t STATE0 = uint256_t(0x69879d90d86d7e20, 0x384230e4dc4235d9, 0x7666b78504e22efe, 0x6eca294b409e4d04);
 // 2^256 / phi
const uint256_t PHI_INV = uint256_t(0x9e3779b97f4a7c15,  0xf39cc0605cedc834, 0x1082276bf3a2725, 0x1f86c6a11d0c18e9);

std::string exename;
int ret = 0;

int output_error(const char* msg_fmt, ...) {
  fprintf(stderr, "%s: ", exename.c_str());
  va_list args;
  va_start(args, msg_fmt);
  vfprintf(stderr, msg_fmt, args);
  va_end(args);
  fprintf(stderr, "\n");
  ret = 1;
  return 0;
}

template<typename T>
T ch(T x, T y, T z) {
  return ((x & y) ^ (~x & z));
}
template<typename T>
T maj(T x, T y, T z) {
  return ((x & y) ^ (x & z) ^ (y & z));
}

uint256_t rotshl(uint256_t a, uint32_t b) {
  b &= 255;
  if (b == 0) return a;
  return (a << b) | (a >> (256 - b));
}

uint256_t do_nonlinear(uint256_t chain, uint256_t state) {
    uint64_t a = chain.u64_0();
    uint64_t b = chain.u64_1();
    uint64_t c = chain.u64_2();
    uint64_t d = chain.u64_3();
    uint64_t e = state.u64_0();
    uint64_t f = state.u64_1();
    uint64_t g = state.u64_2();
    uint64_t h = state.u64_3();
    a ^= ch(b, c, d) ^ maj(e, f, g);
    b ^= ch(c, d, e) ^ maj(f, g, h);
    c ^= ch(d, e, f) ^ maj(g, h, a);
    d ^= ch(e, f, g) ^ maj(h, a, b);
    e ^= ch(f, g, h) ^ maj(a, b, c);
    f ^= ch(g, h, a) ^ maj(b, c, d);
    g ^= ch(h, a, b) ^ maj(c, d, e);
    h ^= ch(a, b, c) ^ maj(d, e, f);
    return uint256_t(e, f, h, g);
}

uint256_t round_func(uint256_t chain, uint256_t state) {
  for (int32_t r = 0; r < NR_ROUND; r++) {
    state = do_nonlinear(chain, state);
    state += rotshl(state, 13) ^ rotshl(state, 57) ^ rotshl(state, 131);
    state ^= rotshl(state, 173) ^ rotshl(state, 199);
    state ^= PHI_INV * (r + 1);
  }
  return state;
}

uint256_t compress(FILE* input_fp, std::string filename, int& error) {
  uint256_t h = H0;
  uint64_t bit_len = 0;
  uint8_t pad = 1;

  for (int b = 0; ; b++) {
    uint256_t state = STATE0;
    uint8_t byte;
    int nr_read;
    bool end = false;
    for (int i = 0; i < BLOCK_SIZE; i++) {
      nr_read = fread(&byte, 1, 1, input_fp);
      if (nr_read == 0) {
        byte = pad;
        pad = 0;
        end = true;
      } else {
        bit_len += 8;
      }

      state ^= byte;
      state += rotshl(state, 13) ^ rotshl(state, 57) ^ rotshl(state, 173);
    }

    (h += round_func(h, state)) ^= PHI_INV * (b + 1);
    if (end) break;
  }


  h ^= ((uint256_t) bit_len << 128) | bit_len;

  for (int i = 0; i < 8; i++) {
    h = round_func(h, h);
  }

  error = 0;
  if (ferror(input_fp)) {
    output_error("unkown error occurred when reading file `%s`.", filename.c_str());
    error = 1;
  }

  return h;
}

int output_line(uint256_t hash, std::string filename) {
  // TODO: use `ls --quoting=shell-escape` style to escape filename
  fprintf(stdout, "%016" PRIx64 "%016" PRIx64 "%016" PRIx64 "%016" PRIx64 "  %s\n",
    hash.u64_3(), hash.u64_2(), hash.u64_1(), hash.u64_0(), filename.c_str());
  return 0;
}

struct CheckLine {
  uint256_t hash; std::string filename;
};

int getline(char* buf, FILE* in) {
  char c, *p = buf;
  while (c = fgetc(in), c == ' ');
  for (; c != '\n' && c != '\r' && c != EOF; c = fgetc(in)) *p++ = c;
  return p - buf;
}

std::vector<CheckLine> analysis_checksum_file(FILE* checksum_fp) {
  std::vector<CheckLine> res;

  uint64_t u64_3, u64_2, u64_1, u64_0;
  static char filename[512];

  while (!feof(checksum_fp)) {
    int ret = fscanf(checksum_fp, "%016" PRIx64 "%016" PRIx64 "%016" PRIx64 "%016" PRIx64 "  %s",
      &u64_3, &u64_2, &u64_1, &u64_0, filename);
    if (ret != 5) {
      static char line[512];
      int line_size = getline(line, checksum_fp);
      if (line_size > 0 && line[0] != '#') {
        output_error("failed to parse line `%*s`. skipped.", line);
      }
      continue;
    }
    // TODO: use `ls --quoting=shell-escape` style to escape filename
    res.push_back({ uint256_t(u64_3, u64_2, u64_1, u64_0), filename });
  }

  return res;
}

FILE* fopen_with_log(const char* filename, const char* mode) {
  if (std::filesystem::is_directory(filename)) {
    output_error("`%s` is a dir.", filename);
    return nullptr;
  }
  FILE* fp = fopen(filename, mode);
  if (fp == nullptr) {
    output_error("cannot open or read file `%s`.", filename);
  }
  return fp;
}

int main(int argc, char** argv) {
  exename = argv[0];
  auto shift = [&]() { argc--; argv++; };

  bool stdin_occurred = false;
  bool escape_mode = false;
  bool check_mode = false;

  struct FileWithName { FILE* fp; std::string name; };
  std::vector<FileWithName> input_files;

  for(shift(); argc; shift()) {
    std::string arg = argv[0];
    if (!escape_mode && arg == "--") escape_mode = true;
    else if (!escape_mode && (arg == "-c" || arg == "--check")) check_mode = true;
    else if (!escape_mode && (arg == "-h" || arg == "--help")) {
      fprintf(stdout, "Usage: %s [-h|--help] [-c|--check] [<FILE>]...\n", exename.c_str());
      return 0;
    } else {
      if (!escape_mode && arg == "-") {
        if (!stdin_occurred) {
          input_files.push_back({stdin, "-"});
          stdin_occurred = true;
        }
        continue;
      }
      FILE* fp = fopen_with_log(arg.c_str(), "rb");
      if (fp == nullptr) continue;
      input_files.push_back({fp, arg});
    }
  }

  if (ret == 0 && input_files.size() == 0) input_files.push_back({stdin, "-"});

  if (check_mode) {
    for (auto& checksum_file : input_files) {
      auto files = analysis_checksum_file(checksum_file.fp);
      for (auto file : files) {
        FILE* fp = fopen_with_log(file.filename.c_str(), "rb");
        if (fp == nullptr) continue;
        int error = 0;
        uint256_t hash = compress(fp, file.filename, error);
        if (!error) fprintf(stdout, "%s: %s\n",
          file.filename.c_str(), hash == file.hash ? "OK" : "FAILED");
        ret |= error || hash != file.hash;
      }
    }
  } else {
    for (auto& file : input_files) {
      int error = 0;
      auto hash = compress(file.fp, file.name, error);
      if (!error) output_line(hash, file.name);
    }
  }

  for (auto& input_file : input_files) {
    if (input_file.fp && input_file.fp != stdin) fclose(input_file.fp);
  }

  return ret;
}
